# Generated by Django 5.0.7 on 2024-08-09 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=9)),
                ('end_time', models.TimeField(default=9)),
                ('sender_message', models.CharField()),
                ('receiver_message', models.CharField()),
            ],
        ),
    ]
