# Generated by Django 5.0.7 on 2024-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newchat',
            name='end_time',
            field=models.TimeField(default=43),
        ),
        migrations.AlterField(
            model_name='newchat',
            name='start_time',
            field=models.TimeField(default=43),
        ),
    ]
